"""initial schema: all 29 tables

Revision ID: 011c661e4753
Revises: 
Create Date: 2026-05-25 13:15:58.530160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011c661e4753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_levels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rank')
    )
    op.create_table('job_positions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seniority_levels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('rank')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_min', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('basic_max', sa.Integer(), nullable=False),
    sa.Column('intermediate_min', sa.Integer(), nullable=False),
    sa.Column('intermediate_max', sa.Integer(), nullable=False),
    sa.Column('advanced_min', sa.Integer(), nullable=False),
    sa.Column('advanced_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('advanced_min = intermediate_max + 1', name='ck_skills_advanced_min_follows_intermediate_max'),
    sa.CheckConstraint('intermediate_min = basic_max + 1', name='ck_skills_intermediate_min_follows_basic_max'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_skills_category_name')
    )
    op.create_index('ix_skills_category_id', 'skills', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'learner'"), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('seniority_id', sa.UUID(), nullable=True),
    sa.Column('job_position_id', sa.UUID(), nullable=True),
    sa.Column('employee_level_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'learner')", name='ck_users_role_valid'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_level_id'], ['employee_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seniority_id'], ['seniority_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_department_id', 'users', ['department_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_sessions_updated_at', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_classes_end_date_after_start_date'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classes_is_active', 'classes', ['is_active'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('active_version_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_category_id', 'documents', ['category_id'], unique=False)
    op.create_index('ix_documents_is_active', 'documents', ['is_active'], unique=False)
    op.create_table('skill_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('cumulative_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_level', sa.String(length=20), server_default=sa.text("'basic'"), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_level IN ('basic', 'intermediate', 'advanced')", name='ck_skill_scores_current_level_valid'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_index('ix_skill_scores_skill_id', 'skill_scores', ['skill_id'], unique=False)
    op.create_index('ix_skill_scores_user_id', 'skill_scores', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_chat_messages_role_valid'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_table('class_members',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'user_id')
    )
    op.create_index('ix_class_members_user_id', 'class_members', ['user_id'], unique=False)
    op.create_table('daily_quiz_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_department_id', sa.UUID(), nullable=True),
    sa.Column('target_seniority_id', sa.UUID(), nullable=True),
    sa.Column('target_job_position_id', sa.UUID(), nullable=True),
    sa.Column('target_employee_level_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('push_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Asia/Ho_Chi_Minh'"), nullable=False),
    sa.Column('expiry_hours', sa.Integer(), server_default=sa.text('24'), nullable=False),
    sa.Column('question_count', sa.SmallInteger(), server_default=sa.text('5'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_daily_quiz_configs_end_date_after_start'),
    sa.CheckConstraint('expiry_hours > 0', name='ck_daily_quiz_configs_expiry_hours_positive'),
    sa.CheckConstraint('question_count > 0', name='ck_daily_quiz_configs_question_count_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_employee_level_id'], ['employee_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_job_position_id'], ['job_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_seniority_id'], ['seniority_levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_quiz_configs_is_active', 'daily_quiz_configs', ['is_active'], unique=False)
    op.create_index('ix_daily_quiz_configs_target_department_id', 'daily_quiz_configs', ['target_department_id'], unique=False)
    op.create_index('ix_daily_quiz_configs_target_employee_level_id', 'daily_quiz_configs', ['target_employee_level_id'], unique=False)
    op.create_index('ix_daily_quiz_configs_target_job_position_id', 'daily_quiz_configs', ['target_job_position_id'], unique=False)
    op.create_index('ix_daily_quiz_configs_target_seniority_id', 'daily_quiz_configs', ['target_seniority_id'], unique=False)
    op.create_table('document_skills',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('document_id', 'skill_id')
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('processing_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mime_type IN ('application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')", name='ck_document_versions_mime_type_valid'),
    sa.CheckConstraint("processing_status IN ('pending', 'processing', 'ready', 'failed')", name='ck_document_versions_processing_status_valid'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('document_id', 'version_number')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_exercises_end_after_start'),
    sa.CheckConstraint('pass_score >= 0 AND pass_score <= total_points', name='ck_exercises_pass_score_within_total'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_class_id', 'exercises', ['class_id'], unique=False)
    op.create_index('ix_exercises_end_time', 'exercises', ['end_time'], unique=False)
    op.create_index('ix_exercises_start_time', 'exercises', ['start_time'], unique=False)
    op.create_table('daily_quizzes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['daily_quiz_configs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'quiz_date', name='uq_daily_quizzes_config_quiz_date')
    )
    op.create_index('ix_daily_quizzes_expires_at', 'daily_quizzes', ['expires_at'], unique=False)
    op.create_index('ix_daily_quizzes_quiz_date', 'daily_quizzes', ['quiz_date'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('embedded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id', 'version_number'], ['document_versions.document_id', 'document_versions.version_number'], name='fk_document_chunks_document_version', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', 'chunk_index', name='uq_document_chunks_doc_version_index')
    )
    op.create_index('ix_document_chunks_document_version', 'document_chunks', ['document_id', 'version_number'], unique=False)
    op.create_index('ix_document_chunks_vector_id', 'document_chunks', ['vector_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_version_number', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id', 'source_version_number'], ['document_versions.document_id', 'document_versions.version_number'], name='fk_questions_source_document_version', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'order_index', name='uq_questions_exercise_order_index')
    )
    op.create_index('ix_questions_exercise_id', 'questions', ['exercise_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('is_late', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', 'attempt_number', name='uq_submissions_user_exercise_attempt')
    )
    op.create_index('ix_submissions_exercise_id', 'submissions', ['exercise_id'], unique=False)
    op.create_index('ix_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_table('chat_message_citations',
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('document_chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.REAL(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('chat_message_id', 'document_chunk_id')
    )
    op.create_index('ix_chat_message_citations_chat_message_id', 'chat_message_citations', ['chat_message_id'], unique=False)
    op.create_index('ix_chat_message_citations_document_chunk_id', 'chat_message_citations', ['document_chunk_id'], unique=False)
    op.create_table('daily_quiz_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('daily_quiz_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_version_number', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quiz_id'], ['daily_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id', 'source_version_number'], ['document_versions.document_id', 'document_versions.version_number'], name='fk_daily_quiz_questions_source_document_version', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_quiz_id', 'order_index', name='uq_daily_quiz_questions_quiz_order_index')
    )
    op.create_index('ix_daily_quiz_questions_daily_quiz_id', 'daily_quiz_questions', ['daily_quiz_id'], unique=False)
    op.create_table('daily_quiz_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('daily_quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_late', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quiz_id'], ['daily_quizzes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_quiz_id', 'user_id', name='uq_daily_quiz_submissions_quiz_user')
    )
    op.create_index('ix_daily_quiz_submissions_daily_quiz_id', 'daily_quiz_submissions', ['daily_quiz_id'], unique=False)
    op.create_index('ix_daily_quiz_submissions_user_id', 'daily_quiz_submissions', ['user_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_label', sa.String(length=5), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'option_label', name='uq_question_options_question_label')
    )
    op.create_index('ix_question_options_question_id', 'question_options', ['question_id'], unique=False)
    op.create_table('daily_quiz_question_options',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('daily_quiz_question_id', sa.UUID(), nullable=False),
    sa.Column('option_label', sa.String(length=5), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quiz_question_id'], ['daily_quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_quiz_question_id', 'option_label', name='uq_daily_quiz_question_options_question_label')
    )
    op.create_index('ix_daily_quiz_question_options_daily_quiz_question_id', 'daily_quiz_question_options', ['daily_quiz_question_id'], unique=False)
    op.create_table('skill_score_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('daily_quiz_submission_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type = 'exam' AND submission_id IS NOT NULL AND daily_quiz_submission_id IS NULL) OR (source_type = 'daily_quiz' AND daily_quiz_submission_id IS NOT NULL AND submission_id IS NULL)", name='ck_skill_score_history_source_consistency'),
    sa.CheckConstraint("source_type IN ('exam', 'daily_quiz')", name='ck_skill_score_history_source_type_valid'),
    sa.ForeignKeyConstraint(['daily_quiz_submission_id'], ['daily_quiz_submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_score_history_created_at', 'skill_score_history', ['created_at'], unique=False)
    op.create_index('ix_skill_score_history_user_skill', 'skill_score_history', ['user_id', 'skill_id'], unique=False)
    op.create_table('submission_answers',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'question_id')
    )
    op.create_table('daily_quiz_submission_answers',
    sa.Column('daily_quiz_submission_id', sa.UUID(), nullable=False),
    sa.Column('daily_quiz_question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quiz_question_id'], ['daily_quiz_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['daily_quiz_submission_id'], ['daily_quiz_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['daily_quiz_question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('daily_quiz_submission_id', 'daily_quiz_question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_quiz_submission_answers')
    op.drop_table('submission_answers')
    op.drop_index('ix_skill_score_history_user_skill', table_name='skill_score_history')
    op.drop_index('ix_skill_score_history_created_at', table_name='skill_score_history')
    op.drop_table('skill_score_history')
    op.drop_index('ix_daily_quiz_question_options_daily_quiz_question_id', table_name='daily_quiz_question_options')
    op.drop_table('daily_quiz_question_options')
    op.drop_index('ix_question_options_question_id', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_daily_quiz_submissions_user_id', table_name='daily_quiz_submissions')
    op.drop_index('ix_daily_quiz_submissions_daily_quiz_id', table_name='daily_quiz_submissions')
    op.drop_table('daily_quiz_submissions')
    op.drop_index('ix_daily_quiz_questions_daily_quiz_id', table_name='daily_quiz_questions')
    op.drop_table('daily_quiz_questions')
    op.drop_index('ix_chat_message_citations_document_chunk_id', table_name='chat_message_citations')
    op.drop_index('ix_chat_message_citations_chat_message_id', table_name='chat_message_citations')
    op.drop_table('chat_message_citations')
    op.drop_index('ix_submissions_user_id', table_name='submissions')
    op.drop_index('ix_submissions_exercise_id', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_questions_exercise_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_document_chunks_vector_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_version', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_daily_quizzes_quiz_date', table_name='daily_quizzes')
    op.drop_index('ix_daily_quizzes_expires_at', table_name='daily_quizzes')
    op.drop_table('daily_quizzes')
    op.drop_index('ix_exercises_start_time', table_name='exercises')
    op.drop_index('ix_exercises_end_time', table_name='exercises')
    op.drop_index('ix_exercises_class_id', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('document_versions')
    op.drop_table('document_skills')
    op.drop_index('ix_daily_quiz_configs_target_seniority_id', table_name='daily_quiz_configs')
    op.drop_index('ix_daily_quiz_configs_target_job_position_id', table_name='daily_quiz_configs')
    op.drop_index('ix_daily_quiz_configs_target_employee_level_id', table_name='daily_quiz_configs')
    op.drop_index('ix_daily_quiz_configs_target_department_id', table_name='daily_quiz_configs')
    op.drop_index('ix_daily_quiz_configs_is_active', table_name='daily_quiz_configs')
    op.drop_table('daily_quiz_configs')
    op.drop_index('ix_class_members_user_id', table_name='class_members')
    op.drop_table('class_members')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_skill_scores_user_id', table_name='skill_scores')
    op.drop_index('ix_skill_scores_skill_id', table_name='skill_scores')
    op.drop_table('skill_scores')
    op.drop_index('ix_documents_is_active', table_name='documents')
    op.drop_index('ix_documents_category_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_classes_is_active', table_name='classes')
    op.drop_table('classes')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_updated_at', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_department_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_skills_category_id', table_name='skills')
    op.drop_table('skills')
    op.drop_table('seniority_levels')
    op.drop_table('job_positions')
    op.drop_table('employee_levels')
    op.drop_table('departments')
    op.drop_table('categories')
    # ### end Alembic commands ###
